### ISSUE TITLE
Can this extension work for FunCaptcha in iframe?

### ISSUE THREAD

**Issue by honest888** [zfcsoftware/funcaptcha-solver#2]
Hello, thanks for your effort. 
I wonder this extension can work with FunCaptcha in iframe.
For example, in outlook FunCaptcha, the FunCatcha is in iframe. 
So, do you think, your extension can work for this?

**Comment by mdervisaygan** [comment]
Hello, yes it works in any iframe. Chrome plugins already have this feature. It works fine, but orbit captcha is not recognized by cap.guru, so it cannot solve it at the moment. It solves the others.

**Comment by honest888** [comment]
Oh. Thanks for your reply.
If so, do you think, this extension can't work for outlook funCaptcha?

**Comment by honest888** [comment]
```
window.onload = () => {
    if (document.URL.includes("arkoselabs")) solveFuncaptcha()
}
```
This is your code. 
So, I think, your extension can't work for URL page that doesn't include "arkoselabs".
As you know, when the FunCaptcah is in iframe, page url doesn't include "arkoselabs" string.

**Comment by mdervisaygan** [comment]
> ```
> window.onload = () => {
>     if (document.URL.includes("arkoselabs")) solveFuncaptcha()
> }
> ```
> 
> This is your code. So, I think, your extension can't work for URL page that doesn't include "arkoselabs". As you know, when the FunCaptcah is in iframe, page url doesn't include "arkoselabs" string.

https://github.com/zfcsoftware/funcaptcha-solver/blob/7668e29b6b8adfda030eb97816baac107e758bdc/manifest.json#L10

Chrome extensions also treat iframes as pages. If the onload event all_frames is true, it works on all iframes and the page. The arkose captcha is already in the iframe. Since the plugin works, it can work in iframe.  Please test it first.

**Comment by honest888** [comment]
Thanks for your kind reply.
